env:
    MANIFEST:
    DT_LINK:
    DT_PATH:
    DEVICE:
    OEM:
    TARGET:
    EXTRA_CMD:

task:
  name: envsetup
  persistent_worker:
    labels:
      name: ubuntu
    isolation:
      container:
        image: ubuntu:20.04
        cpu: 4
        memory: 8G
    
    init_script:
        -env
    
    env_script:
        - sudo apt update && sudo apt install git aria2 rsync -y
        - git config --global user.name "Sushrut1101"
        - git config --global user.email "guptasushrut@gmail.com"
        - git clone https://github.com/akhilnarang/scripts.git ~/scripts
        - cd ~/scripts
        - sudo bash setup/android_build_env.sh
        - cd ~

