env:
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
    FOX_BRANCH: fox_11.0
    SYNC_BRANCH: 11.0
    SYNC_PATH: $HOME/work # Full absolute path. Use "$HOME" instead of "~".
    DT_LINK: https://github.com/OrangeFoxRecovery/device_xiaomi_sweet.git -b fox_11.0
    DEVICE: sweet
    OEM: xiaomi
    DT_PATH: device/$OEM/$DEVICE
    TARGET: recoveryimage
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: ~/work/.ccache
    EXTRA_CMD: git clone https://github.com/OrangeFoxRecovery/Avatar.git misc
    J_VAL: 16
    OUTPUT: OrangeFox*.zip

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m  
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Clone-Dependencies_script:
      - git clone https://github.com/OrangeFoxRecovery/Recovery-Builder-Common.git common

  Sync_script:
      - bash common/sync.sh

  Build_script:
      - bash common/build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash common/upload.sh
