env:
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
    FOX_BRANCH: fox_11.0
    SYNC_BRANCH: 11.0
    SYNC_PATH: $HOME/work
    DT_LINK: https://github.com/OrangeFoxRecovery/device_xiaomi_sweet.git -b fox_11.0
    DEVICE: sweet
    OEM: xiaomi
    DT_PATH: device/$OEM/$DEVICE
    TARGET: recoveryimage
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: ~/work/.ccache
    EXTRA_CMD: git clone https://github.com/OrangeFoxRecovery/Avatar.git misc
    J_VAL: 16
    OUTPUT: OrangeFox*.zip 

task:
  name: "Recovery Build"
  timeout_in: 120m  
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Build_script:
      - bash build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash upload.sh
