env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[5218a731893c3bbf0541e9ac5e7b5a97012316a5be807b6f4e0e461ea6134a694161a2c42cb175ce296d8936c608f5a8]
    TG_TOKEN: ENCRYPTED[36039b97c1d120220488cc45674a8b73aa0305463b37cb0620889257654224f0faa5a51306c23360cc12ebca010f9f84]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/AOSP-Silicon/OrangeFox-CI/main/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/AOSP-Silicon/OrangeFox-CI/main/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/AOSP-Silicon/OrangeFox-CI/main/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/AOSP-Silicon/OrangeFox-CI/main/scripts/upload.sh)"
